# Constants
COORDINATOR_URL = 'https://4shells.com'
DATA: str = ''
DATA_CACHIPFS: str = ''
DATA_CACHIPFS_REPO: str = ''
DATA_EPHEMERAL: str = ''
CACHIPFS_API_PORT: int = 0
CACHIPFS_GATEWAY_PORT: int = 0
CACHIPFS_NODE_PORT: int = 0
CACHIPFS_SWARM_PORT: int = 0
